### ISSUE TITLE
[Feature] Config Web UI for normal mode and setup mode

### ISSUE THREAD

**Issue by yakumo-saki** [yakumo-saki/EnvBoyX#33]
## Pitch

* Enable web ui in normal mode

## Motivation

* In normal mode, reconfigurable via API only, its not good UX

## What to change

- ~Split minimal setup and full setup (WiFi setup only)~
- Enable config api on setup mode
- Rewrite web ui by javascript
- Refactor all URL to clean url

## TO-DO

- [x] Split HTML from code is needed...
- [x] How to automatically upload newest html files to ESP module ? (on platformIO upload button
- [x] #112
- [x] #104 hide PSK Key on setup
- [x] #111
- [x] #106
- [x] Change all URLs in modern manner.
