### ISSUE TITLE
[Feature] Auto dimmer

### ISSUE THREAD

**Issue by yakumo-saki** [yakumo-saki/EnvBoyX#36]
## AS-IS

* No dimmer.

## TO-BE

* Precondition: Luminous sensor is enabled. 
* Low lux continues some duration, set brightness to low value (dimming)
* After dimming, and lux is not low during some duration, set brightness to normal value. 

## TBD

- [x] Low lux threshold (under 10lux?)
- [x] Some duration (30 sec?)
- [x] Make above values are configurable?

## TODO

- [x] Add "Dimmed brightness value" to config
- [x] Add "Auto dimmer threshold" to config ( -1 or lower value to disable auto dimmer)
- [x] Change brightness to brightness (normal)

## NOTE

* To prevent OLED displays burn-in

**Comment by yakumo-saki** [comment]
Add config memo

- [ ] 1. Struct（ここ）
- [ ] 2. Setup HTML          http_setup_web_get.cpp http_setup_get_root_content
- [ ] 3. Setup POST後の表示   http_setup_web_post.cpp http_setup_post_root_content
- [ ] 4. Web API             http_api_backup_config
- [ ] 5. Web API             updateConfig
- [ ] 6. Write Config        _create_config_json
- [ ] 7. Read Config         read_config_file
- [ ] 8. Print config        print_config
- [ ] 9. Config version      global.cpp
