### ISSUE TITLE
[META] Value check when config set

### ISSUE THREAD

**Issue by yakumo-saki** [yakumo-saki/EnvBoyX#87]
## problem

* Config::set has no validation

## about to change

- [x] Add validation to Config::set 
- [x] Add validation error handling on setup web. 
- [x] Add validation error handling on web api
